name: PR Description Check
on:
  pull_request:
    types: [opened, edited]
jobs:
  pr-description-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check PR Description
        run: |
          pr_description="${{ github.event.pull_request.body }}"
          pr_description=$(echo "$pr_description" | tr -d '"')
          
          if echo "$pr_description" | awk 'BEGIN { RS = "" } /## Description[[:space:]]+(.*)[[:space:]]+## Jira Links/ {
              match($0, /## Description[[:space:]]+(.*)[[:space:]]+## Jira Links/, arr);
              gsub(/^[[:space:]]+|[[:space:]]+$/, "", arr[1]);
              if (length(arr[1]) < 15) {
                  exit 0;
              }
              exit 1;
          }'; then
            echo "PR description: $pr_description"
            echo "Result: PR description length should be more than 15 characters"
            exit 1
          fi
          if ! echo "${{ github.event.pull_request.title }}" | grep -E '[A-Z]+-[0-9]+'; then
            echo "PR title does not contain a Jira title in the format: ABCD-1234"
            exit 1
          fi
          if ! echo "$pr_description" | grep -Eq '\[\s*x\s*\]'; then
            echo "Please tick at least 1 checkbox in the checklist"
            exit 1
          fi
          if ! echo "$pr_description" | grep -E 'https?:\/\/(.*).atlassian.net\/browse\/[A-Z]+-[0-9]+'; then
            echo "PR description does not contain a Jira HTTP link"
            exit 1
          fi
          if ! echo "$pr_description" | grep -Eq '## Changes Made'; then
            echo "PR description does not contain a 'Changes Made' heading"
            exit 1
          fi
